version: '3.6'

services:
  app_register:
      container_name: app_registry
      build: ./service-registry/
      ports:
        - "8761:8761"
  app_gateway:
      container_name: app_gateway
      build: ./service-gateway/
      ports:
        - "9191:9191"
      depends_on:
        - app_register
